# WARNING!
# This is a development version of THE Bigcapital docker-compose.yml file.
# Avoid using this file in your production environment.
# We're exposing here sensitive ports and mounting code volumes for rapid development and debugging of the server stack.

version: '3.3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_DATABASE=${SYSTEM_DB_NAME}
        - MYSQL_USER=${DB_NAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql/:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'

  mongo:
    build: ./docker/mongo
    expose:
      - '27017'
    volumes:
      - ./data/mongo/:/var/lib/mongodb
    ports:
      - '27017:27017'

  redis:
    build:
      context: ./docker/redis
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data